### ISSUE TITLE
please use prefix 'yambo.' for entry points

### ISSUE THREAD

**Issue by ltalirz** [yambo-code/yambo-aiida#124]
the plugin currently provides a couple of entry points that aren't prefixed with 'yambo.'
https://travis-ci.org/aiidateam/aiida-registry/jobs/591463873#L416-L419

please consider renaming them

**Comment by mikibonacci** [comment]
@mikeatm do you know something about that? I don't see these entry points

**Comment by ltalirz** [comment]
looking at your `setup.json`, I agree - this looks fine and the travis report above was because of too strict rules on the registry (it should be checking only the entry point groups starting with `aiida.`).

I fixed this in the registry a few days ago - you should be fine. thanks for checking !

**Comment by mikeatm** [comment]
> @mikeatm do you know something about that? I don't see these entry points

Looks like  its already solved, however these are defined at: 
[here](https://github.com/yambo-code/yambo-aiida/blob/master/setup.json#L48-L51) and  implemented in these files: [here](https://github.com/yambo-code/yambo-aiida/tree/master/aiida_yambo/commands)
