### ISSUE TITLE
consider switching to gitflow model for branching

### ISSUE THREAD

**Issue by ltalirz** [yambo-code/yambo-aiida#127]
The main practical reason: the AiiDA registry should display the information of your latest release.
For almost all other plugins, this is achieved by simply taking the setup.json from the `master` branch of the repository.

In your case, I notice you update the master branch in between release.

My suggestion would be to do development in the `develop` branch instead, and to merge `develop` into master only when doing a release (see the [gitflow model](https://nvie.com/posts/a-successful-git-branching-model/)).

**Comment by mikibonacci** [comment]
From now on I'll follow the gitflow model, thank you! 
A question: I've seen that in the AiiDA registry the aiida-yambo has:

> "plugin_info": "https://raw.github.com/yambo-code/yambo-aiida/develop/setup.json"

so: develop instead master. But now the master branch is updated...  Do I have to change that?

**Comment by ltalirz** [comment]
I see - indeed I didn't even notice this.

Yes, please make a PR to switch to `master`.
