### ISSUE TITLE
please release pinned aiida-qe dependency

### ISSUE THREAD

**Issue by ltalirz** [yambo-code/yambo-aiida#163]
The aiida-quantumespresso dependency is currently pinned to one specific alpha version
https://github.com/yambo-code/yambo-aiida/blob/2c5ec08b704d2860d26f768f5423ef8129c4abb7/setup.json#L30

This caused conflicts in Quantum Mobile (e.g. now there is aiida-qe 3.0.0a6).

As a rule of thumb, for dependencies following semantic versioning do not lock down the dependency to more than the major version.
E.g. use something like `aiida-quantumespresso>=3.0.0a6,<4.0`.

One exception to the rule is dependencies for linters/formatters in pre-commit, which may change some rules between minor versions are relevant only to plugin developers.

**Comment by ltalirz** [comment]
Also, please add the "Framework :: AiiDA" trove classifier to the setup.json

**Comment by mikibonacci** [comment]
Done! sorry for the late update @ltalirz
