### ISSUE TITLE
Manual input start from yambo does not work in yamboworkflow

### ISSUE THREAD

**Issue by AntimoMarrazzo** [yambo-code/yambo-aiida#44]

**Comment by mikeatm** [comment]
Please check the new changes this recent  merge on develop  https://github.com/yambo-code/yambo-aiida/pull/59
See if it  fixes the problem for you.

**Comment by mikeatm** [comment]
@AntimoMarrazzo  i need to understand one of the cases where this does not work, currently  yambowf will restart from a failed/incomplete  calc, but if gived a complete calc it will assume all is good and complete and will simply be a noop, what case im i missing?

**Comment by mikeatm** [comment]
@AntimoMarrazzo  any  word on this?  would be nice to have more details
