### ISSUE TITLE
please make a first release

### ISSUE THREAD

**Issue by ltalirz** [yambo-code/yambo-aiida#50]
Hi guys, we've already added the aiida plugins of fleur, siesta, qe and cp2k in the marvel VM.
Could you please make a release of aiida-yambo so that we can add it as well?
As a starting point, a release on github would be sufficient.
Bonus points for a release on PyPI :-)

P.S. If possible, rename the repo to `aiida-yambo` in order to follow the standard adopted by the other plugins.

**Comment by mikeatm** [comment]
@ltalirz  will do,  im finalizing some interface, and i will make the first release soon after, should take at most some hours.

**Comment by mikeatm** [comment]
This has been done. though not on PyPI
