### ISSUE TITLE
Plotting utility for full convergence workchain

### ISSUE THREAD

**Issue by AntimoMarrazzo** [yambo-code/yambo-aiida#61]

**Comment by mikeatm** [comment]
[10939.txt](https://github.com/yambo-code/yambo-aiida/files/1490586/10939.txt)
@giprandini  looks like  `verdi data parameter export` does not exist?

**Comment by AntimoMarrazzo** [comment]
verdi data export will suffice

**Comment by mikeatm** [comment]
@AntimoMarrazzo 
```$ verdi data  export   10939  
You passed an invalid subcommand to 'verdi data'.
Valid subcommands are:
  remote
  cif
  trajectory
  upf
  bands
  array
  description
  parameter
  structure
  label
```

**Comment by AntimoMarrazzo** [comment]
sorry, verdi export

**Comment by mikeatm** [comment]
[SiFull.zip](https://github.com/yambo-code/yambo-aiida/files/1490673/SiFull.zip)
Here is what works  `verdi  export create  -n 10939  "SiFull"`

**Comment by mikeatm** [comment]
Gianluca, here is where we are,  i fixed the kpoints, but im still not 100% sure what caused it.
The following is a suggestion of course, not sure whether  you had already finished.
[SiFull.21439.zip](https://github.com/yambo-code/yambo-aiida/files/1494563/SiFull.21439.zip)
![conv](https://user-images.githubusercontent.com/8317804/33109412-a9e60b2e-cf41-11e7-84f1-9ce603f029c3.png)

```
import re
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib import gridspec 
import json
import sys

def plotter(fig, gs , ax1,  ind, dep , var):
    fig.suptitle(r'Direct Gap at $\Gamma$', size=14)
    ax1.set_xlim(0,8)
    ax1.set_ylim(0,8)
    ax1.set_ylabel("Energy (eV)")
    ax1.set_xlabel('Convergence space ')
    ax1.plot( ind , dep  , label= var, marker='+'  ) 
    h,l=ax1.get_legend_handles_labels()
    ax1.legend(h,l, loc=2,  ncol=1, prop={'size': 12} )

def read_intp_out():
    fig = plt.figure()
    gs= gridspec.GridSpec(1,1)
    gs.update(wspace =0.3)
    ax1 = fig.add_subplot(gs[0,0]) 
    with open("21439.txt", 'r') as f:
        js = f.read()
    data = json.loads(js)

    dep_kp = np.array(data['kpoints']['energy_widths'] )
    indep_kp = np.array(data['kpoints']['convergence_space']['kpoints'] )
    indep_kp = 1.0/indep_kp
    plotter(fig,gs, ax1, indep_kp, dep_kp,  "kpoints"  )

    indep_fft = np.array(data['fft']['convergence_space']['FFTGvecs'] )
    dep_fft = np.array(data['fft']['energy_widths'] )
    indep_fft = indep_fft + (-indep_fft[0]+indep_kp[-1])
    plotter(fig,gs, ax1, indep_fft , dep_fft, "FFT"  )


    indep_bands = np.array([ el[-1] for el in data['bands']['convergence_space']['GbndRnge'] ] )
    indep_bands = indep_bands+ (-indep_bands[0] + indep_fft[-1])
    dep_bands = np.array(data['bands']['energy_widths'] )
    plotter(fig,gs, ax1, indep_bands, dep_bands,  "Bands"  )

    indep_G = np.array(data['cutoff']['convergence_space']['NGsBlkXp'] )
    indep_G= indep_G + (-indep_G[0] + indep_bands[-1] )
    dep_G = np.array(data['cutoff']['energy_widths'] )
    plotter(fig,gs, ax1, indep_G, dep_G,  "G"  )
    
    plt.xticks([], [])
    plt.ylim(2.0,4.5)
    plt.xlim(0,indep_G[-1])
    #plt.show()
    plt.savefig("Conv")
    plt.close()
    mpl.rcParams.update(mpl.rcParamsDefault)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description='GW QP calculation.')
    args = parser.parse_args()
    read_intp_out()

```
[21439.txt](https://github.com/yambo-code/yambo-aiida/files/1494566/21439.txt)

**Comment by giprandini** [comment]
Hi Mike,
now it looks better. I don't know the kpoint densities used to which k-grid corresponds but it seems that now they are already converged since the first calculation.
Regarding this new example, I noticed that for the cutoff the units are RL instead of Ry, this is probably why the convergence is completely flat. And also the number of bands I noticed it is very small.

I've prepared these two simple functions in case you want to plot separetely the various convergence parameters.

`
import numpy, math , matplotlib
import matplotlib.pyplot as plt

def plot(convergence_parameter,energy_convergence_parameter,name):
    fig, ax = plt.subplots()
    ax.set_xlabel(r'{}'.format(name),size=14)
    ax.set_ylabel(r'Energy',size=14)
    ax.plot(convergence_parameter,energy_convergence_parameter,linestyle='-', marker='o', color='orange', linewidth=2.5, label='{} convergence'.format(name))
    ax.set_xlim(min(convergence_parameter),max(convergence_parameter))
    #ax.set_ylim(0,1)
    plt.legend()
    plt.show()
    plt.close()


def plot_convergergence(uuid):
    '''
    uuid: string with the uuid of the YamboFullConvergenceWorkflow
    '''
    
    wc = load_node(uuid)

    results = wc.out.result  # ParameterData with the results
    
    #bands = results.get_dict()['bands']['convergence_space']['BndsRnXp']
    bands = [i[-1]  for i in results.get_dict()['bands']['convergence_space']['BndsRnXp']]
    energy_bands = results.get_dict()['bands']['energy_widths']

    kpoints_density = results.get_dict()['kpoints']['convergence_space']['kpoints']
    energy_kpoints_density = results.get_dict()['kpoints']['energy_widths']
    
    wcutoff = results.get_dict()['cutoff']['convergence_space']['NGsBlkXp']
    energy_wcutoff = results.get_dict()['cutoff']['energy_widths']
    
    fft = results.get_dict()['fft']['convergence_space']['FFTGvecs']
    energy_fft = results.get_dict()['fft']['energy_widths']

    plot(bands, energy_bands, name='Number of bands')
    plot(kpoints_density, energy_kpoints_density, name='Kpoints')
    plot(wcutoff, energy_wcutoff, name='W cutoff')
    plot(fft, energy_fft, name='FFT')
`

**Comment by mikeatm** [comment]
@giprandini  We need to standardise the units since they are scattered accross the code base and could become an issue all by themselves. why dont you open a new issue where we can agree how to handle units,  whether to let the user decide or agree by convention what units MUST be provided and so on.
