### ISSUE TITLE
outdated link to code on pypi

### ISSUE THREAD

**Issue by ltalirz** [yambo-code/yambo-aiida#88]
Code link on https://pypi.python.org/pypi/aiida-yambo/0.2.4 points to a non-existent bitbucket repo.

Please also add the requirements, at least in terms of the minimum aiida-core version needed, for an example see
https://pypi.python.org/pypi/aiida_siesta/0.9.8

Thanks!
Leo

**Comment by mikeatm** [comment]
Metadata goes missing if the wheel is not uploaded first to pypi,  the  require distributions metadata will be visible then, but is present if you try to install i believe.

**Comment by ltalirz** [comment]
ok, I'm not entirely sure I get what you are saying, but if the requirements are properly taken into account upon installing the package, it's fine

**Comment by mikeatm** [comment]
i mean this line is missing on that page and  the new version,  [here](https://pypi.python.org/pypi/aiida-yambo/0.2.5)
```
Requires Distributions
   pytest (>=3.3.2)
   reentry (>=1.0.2)
   aiida-core[docs,atomic_tools] (>=0.10.0)
```
So part of this issue is solved, but the above lines will appear  when we do the upload in the correct  order: 
```
    python setup.py bdist_wheel upload
    python setup.py sdist upload
```
which was done  in the reverse order, causing the missing info.

**Comment by ltalirz** [comment]
Great, so I guess it will be fixed in the next release
